module.exports = [
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1714999432,
    "hostOnly": false,
    "httpOnly": false,
    "name": "a1",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "187f63d6adcq3wjn1wb2vene66ky03zs66ddn8pg550000370761",
    "id": 1
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1724944845.800958,
    "hostOnly": false,
    "httpOnly": false,
    "name": "gid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "yYWiKqfWy8K8yYWiKqfK0KYUfSAqEVIyEDJhfk2dIdKKTf28v8quMI888qW8WKy8KyJ0yKDK",
    "id": 2
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1722785145.414752,
    "hostOnly": false,
    "httpOnly": true,
    "name": "gid.sign",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "D7/VzvvuxP88aU+JOqXbe/m4X/k=",
    "id": 3
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1690385686,
    "hostOnly": false,
    "httpOnly": false,
    "name": "sec_poison_id",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "6e00075a-28a5-44a6-b698-be715f079bb5",
    "id": 4
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1721908236.659331,
    "hostOnly": false,
    "httpOnly": true,
    "name": "web_session",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "0400697574d8abf5524de440f4364b889df42a",
    "id": 5
},
{
    "domain": ".xiaohongshu.com",
    "hostOnly": false,
    "httpOnly": false,
    "name": "webBuild",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "2.17.8",
    "id": 6
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1714999432,
    "hostOnly": false,
    "httpOnly": false,
    "name": "webId",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "d033be4c61f80c9081b8c2690e5723ea",
    "id": 7
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1690644281,
    "hostOnly": false,
    "httpOnly": false,
    "name": "websectiga",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "a9bdcaed0af874f3a1431e94fbea410e8f738542fbb02df1e8e30c29ef3d91ac",
    "id": 8
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1714999432.307756,
    "hostOnly": false,
    "httpOnly": false,
    "name": "xhsTrackerId",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "c9f631d7-aa14-4c11-b157-d3d63317d83e",
    "id": 9
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1714999432.307783,
    "hostOnly": false,
    "httpOnly": false,
    "name": "xhsTrackerId.sig",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "vcJQLpSqpCp4S7uhMAF_DnqwhSjH53mk2XlJjJBT24o",
    "id": 10
},
{
    "domain": ".xiaohongshu.com",
    "expirationDate": 1721920844,
    "hostOnly": false,
    "httpOnly": false,
    "name": "xsecappid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "xhs-pc-web",
    "id": 11
}
]